name: quickplots
channels:
  - conda-forge
dependencies:
        - numpy
        - matplotlib
        - xarray
        - netcdf4
        - cmocean
        - gsw
        - cfgrib
        - cartopy
        - pandas
        - tqdm
        - geopy
